### ISSUE TITLE
Symfony/FileSystem not found

### ISSUE THREAD

**Issue by AraaCuteUwU** [DavyCraft648/PM-NG#11]
when I start the server, it shows a message that Symfony/Filesystem is not found in PocketMine.php. And the symfony/filesystem in composer.json is not installed in the vendor

**Comment by DavyCraft648** [comment]
you need to use `composer update` to update your `composer.lock`

**Comment by AraaCuteUwU** [comment]
> you need to use `composer update` to update your `composer.lock`

Fix thx, btw can you update it to 1.19.50?

**Comment by DavyCraft648** [comment]
> can you update it to 1.19.50

technically i can, i have updated my server to 1.19.50

however, I'd like to publish it after PMMP update theirs
