### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by AraaCuteUwU** [DavyCraft648/PM-NG#12]
[Server thread/CRITICAL]: TypeError: "pocketmine\world\World::filterViewersForPosition(): Argument #2 ($allowed) must be of type array, null given, called in phar://C:/Users/LENOVO/OneDrive/Documents/project/pm5/PocketMine-MP.phar/src/world/World.php on line 714" (EXCEPTION) in "pmsrc/src/world/World" at line 661

Server crash when i try to use candle

**Comment by DavyCraft648** [comment]
Fixed by cbb23f2d6e91213b434f51baafd1dbb0e4c73c0f
