### ISSUE TITLE
A small question for using the fork

### ISSUE THREAD

**Issue by AzaleeX** [DavyCraft648/PM-NG#14]
I'd like to know how you manage to merge things that pocketmine do without seeing that it's a fork what a small image to ilustrate.
because I'm the creator of [Symply](https://github.com/SymplyX) and I'd like to know how you do it.

## the current repo:
![image](https://github.com/DavyCraft648/PM-NG/assets/82237910/fbe3221b-4242-43ce-9276-933c3c3a3511)
## the repo where you can see that it has a fork:
![image](https://github.com/DavyCraft648/PM-NG/assets/82237910/3fba603f-4ac6-4b40-b153-7bc788991292)

**Comment by Azvyl** [comment]
this might help you https://stackoverflow.com/questions/32948339/merging-a-git-repo-into-another-repo
I don't use command line though,
but I use github in PHPStorm
However, it seems like the steps given in the link are the same

**Comment by AzaleeX** [comment]
but what do you have ?

**Comment by Azvyl** [comment]
> but what do you have ?

what do you mean?

**Comment by AzaleeX** [comment]
how do you do it ?

**Comment by AzaleeX** [comment]
@DavyCraft648 Can you give me more details on how you do it?

**Comment by Azvyl** [comment]
I don't really remember how I did it, this is what I remember:
1. Create a new Github repo (not a fork)
2. Create a new project in PHPStorm from Version Control
![image](https://github.com/DavyCraft648/PM-NG/assets/67502532/7aba115c-28c7-4ef1-9504-5a3311ad93e1)

3. Change the origin remote url to my repo
![image](https://github.com/DavyCraft648/PM-NG/assets/67502532/e5c10e6d-30e0-418f-9dc6-1a0a02021851)

4. Add new remote (Git -> Manage Remotes)
![image](https://github.com/DavyCraft648/PM-NG/assets/67502532/347631a0-cbd7-42a5-bccf-411856a2fbd4)

5. Push commits
![image](https://github.com/DavyCraft648/PM-NG/assets/67502532/523528b4-0b29-4f69-9b82-7cc91df13ef6)


Done.
