### ISSUE TITLE
1.20.70

### ISSUE THREAD

**Issue by GabBiswajit** [DavyCraft648/PM-NG#15]
Add 1.20.70 support, thanks for this pm 🙌

**Comment by Azvyl** [comment]
I included it in the pre-release 3 weeks ago, but I haven't published the code yet

https://github.com/DavyCraft648/PM-NG/releases/tag/1.20.70-r1

**Comment by GabBiswajit** [comment]
Thanks

**Comment by GabBiswajit** [comment]
I hope this can't break my server 🙌
