### ISSUE TITLE
Some plugins don't work on the server

### ISSUE THREAD

**Issue by TheAryqn** [DavyCraft648/PM-NG#19]
Some plugins like MultiWorld don't work on the server.

**Comment by TheAryqn** [comment]
![Screenshot_20240623_214429](https://github.com/DavyCraft648/PM-NG/assets/128404227/4a5e878a-635e-4775-858c-cc0bc56d2d3f)

**Comment by Azvyl** [comment]
this is normal, this fork uses the pm6 branch as its base which removes the use of the legacy enum

https://github.com/DavyCraft648/PM-NG/issues/16#issuecomment-2016763635

**Comment by TheAryqn** [comment]
> this is normal, this fork uses the pm6 branch as its base which removes the use of the legacy enum
> 
> [#16 (comment)](https://github.com/DavyCraft648/PM-NG/issues/16#issuecomment-2016763635)

How can I fix it?
